# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_g <- function(omega, alpha, beta, gamma, returns, g0) {
    .Call('mfGARCH_calculate_g', PACKAGE = 'mfGARCH', omega, alpha, beta, gamma, returns, g0)
}

simulate_r <- function(n_days, n_intraday, alpha, beta, gamma, Z, h0) {
    .Call('mfGARCH_simulate_r', PACKAGE = 'mfGARCH', n_days, n_intraday, alpha, beta, gamma, Z, h0)
}

sum_tau <- function(i, m, theta, phivar, covariate, K) {
    .Call('mfGARCH_sum_tau', PACKAGE = 'mfGARCH', i, m, theta, phivar, covariate, K)
}

sum_tau_zwei <- function(m, theta, phivar, covariate, K) {
    .Call('mfGARCH_sum_tau_zwei', PACKAGE = 'mfGARCH', m, theta, phivar, covariate, K)
}

