# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' calculate_g
#' @description
#' Calculates the short-term component
#' @export calculate_g
calculate_g <- function(omega, alpha, beta, gamma, returns, g0) {
    .Call('mfGARCH_calculate_g', PACKAGE = 'mfGARCH', omega, alpha, beta, gamma, returns, g0)
}

#' @title
#' sum_tau
#' @description
#' Calculates part of the long-term component
#' @export sum_tau
sum_tau <- function(i, m, theta, phivar, covariate, K) {
    .Call('mfGARCH_sum_tau', PACKAGE = 'mfGARCH', i, m, theta, phivar, covariate, K)
}

