# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_g <- function(omega, alpha, beta, gamma, returns, g0) {
    .Call('_mfGARCH_calculate_g', PACKAGE = 'mfGARCH', omega, alpha, beta, gamma, returns, g0)
}

calculate_h_andersen <- function(ndays, delta, mu, theta, omega, lambda, Z, pi, h0) {
    .Call('_mfGARCH_calculate_h_andersen', PACKAGE = 'mfGARCH', ndays, delta, mu, theta, omega, lambda, Z, pi, h0)
}

calculate_p <- function(ndays, delta, mu, Zp, h, p0) {
    .Call('_mfGARCH_calculate_p', PACKAGE = 'mfGARCH', ndays, delta, mu, Zp, h, p0)
}

simulate_r <- function(n_days, n_intraday, alpha, beta, gamma, Z, h0) {
    .Call('_mfGARCH_simulate_r', PACKAGE = 'mfGARCH', n_days, n_intraday, alpha, beta, gamma, Z, h0)
}

simulate_r_rv_as_dependent <- function(n_days, n_intraday, alpha, beta, gamma, Z, h0, K, m, theta, weights, lowfreq, rvol) {
    .Call('_mfGARCH_simulate_r_rv_as_dependent', PACKAGE = 'mfGARCH', n_days, n_intraday, alpha, beta, gamma, Z, h0, K, m, theta, weights, lowfreq, rvol)
}

sum_tau_fcts <- function(i, m, theta, phivar, covariate, K) {
    .Call('_mfGARCH_sum_tau_fcts', PACKAGE = 'mfGARCH', i, m, theta, phivar, covariate, K)
}

sum_tau <- function(m, theta, phivar, covariate, K) {
    .Call('_mfGARCH_sum_tau', PACKAGE = 'mfGARCH', m, theta, phivar, covariate, K)
}

